"""
SURE SAVINGS: Central Authoritative Financial Glossary
Provides language-neutral financial definitions and approved localized terms across all 23 languages.
Gemini and the UI catalogs MUST use these exact terms to prevent inconsistent terminology.
"""
from typing import Dict, Any, Optional

# Authoritative concepts dictionary
FINANCIAL_GLOSSARY: Dict[str, Dict[str, Any]] = {
    "safe_to_save": {
        "concept_key": "safe_to_save",
        "canonical_definition": "The exact portion of surplus income that can be safely transferred into reserves without threatening non-negotiable living expenses or the protected checking floor.",
        "short_definition": "Surplus cash that is 100% safe to lock into reserves today.",
        "terms": {
            "en-IN": "Safe-to-Save",
            "hi-IN": "सुरक्षित बचत राशि",
            "bn-IN": "নিরাপদে সঞ্চয়যোগ্য পরিমাণ",
            "as-IN": "সুৰক্ষিত সঞ্চয় পৰিমাণ",
            "brx-IN": "रैखाथि दोनथुमनाय",
            "doi-IN": "सुरक्षित बचत रकम",
            "gu-IN": "સુરક્ષિત બચત રકમ",
            "kn-IN": "ಸುರಕ್ಷಿತ ಉಳಿತಾಯ ಮೊತ್ತ",
            "ks-IN": "محفوظ بچت کی رقم",
            "kok-IN": "सुरक्षित बचत रक्कम",
            "ml-IN": "സുരക്ഷിതമായി സമ്പാദിക്കാവുന്ന തുക",
            "mni-IN": "কনশিনবা য়াবা শেনফম",
            "mr-IN": "सुरक्षित बचत रक्कम",
            "mai-IN": "सुरक्षित बचत राशि",
            "ne-IN": "सुरक्षित बचत रकम",
            "or-IN": "ସୁରକ୍ଷିତ ସଞ୍ଚୟ ରାଶି",
            "pa-IN": "ਸੁਰੱਖਿਅਤ ਬੱਚਤ ਰਕਮ",
            "sa-IN": "सुरक्षित-सञ्चय-धनम्",
            "sat-IN": "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱥᱟᱸᱪᱟᱣ ᱴᱟᱠᱟ",
            "sd-IN": "محفوظ بچت رقم",
            "ta-IN": "பாதுகாப்பாகச் சேமிக்கக்கூடிய தொகை",
            "te-IN": "సురక్షితంగా దాచదగిన మొత్తం",
            "ur-IN": "محفوظ بچت کی رقم",
        }
    },
    "smart_buffer": {
        "concept_key": "smart_buffer",
        "canonical_definition": "A dynamic multi-tier cash reserve that automatically absorbs dry periods and unexpected income shocks.",
        "short_definition": "Dynamic cash reserve protecting against gig income droughts.",
        "terms": {
            "en-IN": "Smart Buffer",
            "hi-IN": "स्मार्ट बफर",
            "bn-IN": "স্মার্ট বাফার",
            "as-IN": "স্মাৰ্ট বাফাৰ",
            "brx-IN": "स्मार्ट बाफार",
            "doi-IN": "स्मार्ट बफर",
            "gu-IN": "સ્માર્ટ બફર",
            "kn-IN": "ಸ್ಮಾರ್ಟ್ ಬಫರ್",
            "ks-IN": "اسمارٹ بفر",
            "kok-IN": "स्मार्ट बफर",
            "ml-IN": "സ്മാർട്ട് ബഫർ",
            "mni-IN": "স্মার্ত বফর",
            "mr-IN": "स्मार्ट बफर",
            "mai-IN": "स्मार्ट बफर",
            "ne-IN": "स्मार्ट बफर",
            "or-IN": "ସ୍ମାର୍ଟ ବଫର",
            "pa-IN": "ਸਮਾਰਟ ਬਫਰ",
            "sa-IN": "स्मार्ट-मध्यवर्ती-निधिः",
            "sat-IN": "ᱥᱢᱟᱨᱴ ᱵᱟᱯᱷᱟᱨ",
            "sd-IN": "اسمارٽ بفر",
            "ta-IN": "ஸ்மார்ட் பஃபர்",
            "te-IN": "స్మార్ట్ బఫర్",
            "ur-IN": "اسمارٹ بفر",
        }
    },
    "protected_floor": {
        "concept_key": "protected_floor",
        "canonical_definition": "The minimum checking balance threshold reserved strictly for living necessities below which no savings may be withdrawn.",
        "short_definition": "Minimum checking balance safeguarding essential daily needs.",
        "terms": {
            "en-IN": "Protected Cash Floor",
            "hi-IN": "सुरक्षित नकद न्यूनतम स्तर",
            "bn-IN": "সুরক্ষিত নগদ ন্যূনতম সীমা",
            "as-IN": "সুৰক্ষিত নগদ নিম্নতম সীমা",
            "brx-IN": "रैखाथि रोजा गाहाय थाम",
            "doi-IN": "सुरक्षित रोकड़ निचला स्तर",
            "gu-IN": "સુરક્ષિત રોકડ લઘુત્તમ સ્તર",
            "kn-IN": "ರಕ್ಷಿತ ನಗದು ಕನಿಷ್ಠ ಮಿತಿ",
            "ks-IN": "محفوظ نقد کی کم از کم حد",
            "kok-IN": "सुरक्षित रोख किमान मर्यादा",
            "ml-IN": "സംരക്ഷിത പണ അടിത്തറ",
            "mni-IN": "ঙাক-শেনবা শেলগী তংদু লৈতাবা মফম",
            "mr-IN": "संरक्षित रोख किमान मर्यादा",
            "mai-IN": "सुरक्षित नकद निचला स्तर",
            "ne-IN": "सुरक्षित नगद न्यूनतम सीमा",
            "or-IN": "ସୁରକ୍ଷିତ ନଗଦ ନିମ୍ନତମ ସୀମା",
            "pa-IN": "ਸੁਰੱਖਿਅਤ ਨਕਦੀ ਹੇਠਲਾ ਪੱਧਰ",
            "sa-IN": "संरक्षित-रोकड-तलम्",
            "sat-IN": "ᱨᱩᱠᱷᱤᱭᱟᱹ ᱴᱟᱠᱟ ᱞᱟᱛᱟᱨ ᱥᱤᱢᱟᱹ",
            "sd-IN": "محفوظ نقد گھٽ ۾ گھٽ حد",
            "ta-IN": "பாதுகாக்கப்பட்ட பணத் தளம்",
            "te-IN": "రక్షిత నగదు కనీస పరిమితి",
            "ur-IN": "محفوظ نقد کی کم از کم حد",
        }
    },
    "financial_resilience": {
        "concept_key": "financial_resilience",
        "canonical_definition": "Deterministic 0-100 score measuring the user's capacity to absorb volatility shocks, income droughts, and unexpected expenses.",
        "short_definition": "Capacity to survive volatile earnings cycles safely.",
        "terms": {
            "en-IN": "Financial Resilience",
            "hi-IN": "वित्तीय लचीलापन (रेजिलिएंस)",
            "bn-IN": "আর্থিক স্থিতিস্থাপকতা",
            "as-IN": "বিত্তীয় স্থিতিস্থাপকতা",
            "brx-IN": "रांखान्थि रैखाथि गोहो",
            "doi-IN": "माली लचीलापन",
            "gu-IN": "નાણાકીય સ્થિતિસ્થાપકતા",
            "kn-IN": "ಹಣಕಾಸು ಸ್ಥಿತಿಸ್ಥಾಪಕತ್ವ",
            "ks-IN": "مالی لچک",
            "kok-IN": "आर्थिक सहनशीलता",
            "ml-IN": "സാമ്പത്തിക പ്രതിരോധശേഷി",
            "mni-IN": "শেল-থুমগী অকনবা মতিক",
            "mr-IN": "आर्थिक लवचिकता",
            "mai-IN": "वित्तीय लचीलापन",
            "ne-IN": "वित्तीय लचिलोपन",
            "or-IN": "ଆର୍ଥିକ ସ୍ଥିତିସ୍ଥାପକତା",
            "pa-IN": "ਵਿੱਤੀ ਲਚਕੀਲਾਪਣ",
            "sa-IN": "आर्थिक-प्रतिरोध-शक्तिः",
            "sat-IN": "ᱠᱟᱹᱣᱰᱤ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱫᱟᱲᱮ",
            "sd-IN": "مالي لچڪ",
            "ta-IN": "நிதி உறுதிப்பாடு",
            "te-IN": "ఆర్థిక నిలకడ",
            "ur-IN": "مالی لچک",
        }
    },
    "stabilized_income": {
        "concept_key": "stabilized_income",
        "canonical_definition": "The statistically smoothed baseline income derived from irregular gig platform deposits.",
        "short_definition": "Reliable smoothed baseline income across irregular cycles.",
        "terms": {
            "en-IN": "Stabilized Income",
            "hi-IN": "स्थिर आय",
            "bn-IN": "স্থিতিশীল আয়",
            "as-IN": "স্থিতিশীল উপাৰ্জন",
            "brx-IN": "थोंजों खावनाय",
            "doi-IN": "स्थिर आमदनी",
            "gu-IN": "સ્થિર આવક",
            "kn-IN": "ಸ್ಥಿರ ಆದಾಯ",
            "ks-IN": "مستحکم آمدنی",
            "kok-IN": "थिर येणावळ",
            "ml-IN": "സ്ഥിര വരുമാനം",
            "mni-IN": "লেপ্নবা তানবা শেল",
            "mr-IN": "स्थिर उत्पन्न",
            "mai-IN": "स्थिर आमदनी",
            "ne-IN": "स्थिर आम्दानी",
            "or-IN": "ସ୍ଥିର ଆୟ",
            "pa-IN": "ਸਥਿਰ ਆਮਦਨ",
            "sa-IN": "स्थिरीकृता आयः",
            "sat-IN": "ᱛᱷᱤᱨ ᱠᱟᱹᱣᱰᱤ ᱟᱨᱡᱟᱣ",
            "sd-IN": "مستحڪم آمدني",
            "ta-IN": "நிலையான வருமானம்",
            "te-IN": "స్థిరీకరించిన ఆదాయం",
            "ur-IN": "مستحکم آمدنی",
        }
    },
    "liquidity": {
        "concept_key": "liquidity",
        "canonical_definition": "Instantly accessible cash ready to deploy without friction or lockup penalties.",
        "short_definition": "Immediately spendable cash reserves.",
        "terms": {
            "en-IN": "Liquidity",
            "hi-IN": "तरलता (उपलब्ध नकद)",
            "bn-IN": "তারল্য",
            "as-IN": "তাৰল্য",
            "brx-IN": "गोथों रां",
            "doi-IN": "तरलता",
            "gu-IN": "પ્રવાહિતા",
            "kn-IN": "ದ್ರವ್ಯತೆ",
            "ks-IN": "لیکویڈیٹی",
            "kok-IN": "तरलता",
            "ml-IN": "ദ്രവ്യത",
            "mni-IN": "খুদক্তা শিজিন্নবা য়াবা শেল",
            "mr-IN": "तरलता",
            "mai-IN": "तरलता",
            "ne-IN": "तरलता",
            "or-IN": "ତରଳତା",
            "pa-IN": "ਤਰਲਤਾ",
            "sa-IN": "द्रव्यता",
            "sat-IN": "ᱞᱤᱠᱩᱭᱤᱰᱤᱴᱤ",
            "sd-IN": "نقد رواني",
            "ta-IN": "பணப்புழக்கம்",
            "te-IN": "ద్రవ్యత",
            "ur-IN": "نقد دستیابی (لیکویڈیٹی)",
        }
    },
    "buffer_coverage": {
        "concept_key": "buffer_coverage",
        "canonical_definition": "The exact duration (in days or weeks) current reserves can fund living expenses during a total income pause.",
        "short_definition": "Runway of living expenses covered by savings buffer.",
        "terms": {
            "en-IN": "Buffer Coverage",
            "hi-IN": "बफर कवरेज",
            "bn-IN": "বাফার কভারেজ",
            "as-IN": "বাফাৰ সুৰক্ষা কাল",
            "brx-IN": "बाफार खभारेज",
            "doi-IN": "बफर कवरेज",
            "gu-IN": "બફર કવરેજ",
            "kn-IN": "ಬಫರ್ ರಕ್ಷಣೆ ಕಾಲ",
            "ks-IN": "بفر کوریج",
            "kok-IN": "बफर व्याप्ती",
            "ml-IN": "ബഫർ പരിരക്ഷ",
            "mni-IN": "বফর কভরেজ",
            "mr-IN": "बफर कव्हरेज",
            "mai-IN": "बफर कवरेज",
            "ne-IN": "बफर कभरेज",
            "or-IN": "ବଫର ସୁରକ୍ଷା ଅବଧି",
            "pa-IN": "ਬਫਰ ਕਵਰੇਜ",
            "sa-IN": "बफर-आवरणम्",
            "sat-IN": "ᱵᱟᱯᱷᱟᱨ ᱠᱟᱵᱷᱟᱨᱮᱡᱽ",
            "sd-IN": "بفر ڪوريج",
            "ta-IN": "பஃபர் கவரேஜ்",
            "te-IN": "బఫర్ రక్షణ వ్యవధి",
            "ur-IN": "بفر کوریج",
        }
    },
    "income_volatility": {
        "concept_key": "income_volatility",
        "canonical_definition": "Statistical variance measuring swings between peak payout days and platform drought weeks.",
        "short_definition": "Severity of irregular swings in weekly earnings.",
        "terms": {
            "en-IN": "Income Volatility",
            "hi-IN": "आय में उतार-चढ़ाव",
            "bn-IN": "আয়ের অস্থিরতা",
            "as-IN": "উপাৰ্জনৰ অস্থিৰতা",
            "brx-IN": "खावनाय सोलाय-सोल",
            "doi-IN": "आमदनी दा फेरबदल",
            "gu-IN": "આવકમાં વધઘટ",
            "kn-IN": "ಆದಾಯದ ಅನಿಶ್ಚಿತತೆ",
            "ks-IN": "آمدنی کا اتار چڑھاؤ",
            "kok-IN": "येणावळींतलो बदल",
            "ml-IN": "വരുമാന ചാഞ്ചാട്ടം",
            "mni-IN": "শেল তানবদা লৈতাবা তাংবা",
            "mr-IN": "उत्पन्नातील चढ-उतार",
            "mai-IN": "आमदनी मे उतार-चढ़ाव",
            "ne-IN": "आम्दानीको उतारचढाव",
            "or-IN": "ଆୟର ଅସ୍ଥିରତା",
            "pa-IN": "ਆਮਦਨ ਵਿੱਚ ਉਤਰਾਅ-ਚੜ੍ਹਾਅ",
            "sa-IN": "आय-अस्थिरता",
            "sat-IN": "ᱟᱨᱡᱟᱣ ᱨᱮᱱᱟᱜ ᱵᱚᱫᱚᱞ",
            "sd-IN": "آمدني جو لاٿ چاڙهه",
            "ta-IN": "வருமான ஏற்ற இறக்கம்",
            "te-IN": "ఆదాయ అస్థిరత",
            "ur-IN": "آمدنی کا اتار چڑھاؤ",
        }
    },
    "financial_risk": {
        "concept_key": "financial_risk",
        "canonical_definition": "Modeled likelihood of a cash shortfall breach occurring within the forecast window.",
        "short_definition": "Likelihood of cash dropping below protected floor.",
        "terms": {
            "en-IN": "Financial Risk",
            "hi-IN": "वित्तीय जोखिम",
            "bn-IN": "আর্থিক ঝুঁকি",
            "as-IN": "বিত্তীয় সংকটৰ সম্ভাৱনা",
            "brx-IN": "रांखान्थि खैफोद",
            "doi-IN": "माली खतरा",
            "gu-IN": "નાણાકીય જોખમ",
            "kn-IN": "ಹಣಕಾಸು ಅಪಾಯ",
            "ks-IN": "مالی خطرہ",
            "kok-IN": "आर्थिक धोको",
            "ml-IN": "സാമ്പത്തിക നഷ്ടസാധ്യത",
            "mni-IN": "শেল-থুমগী খুদোংথিবা",
            "mr-IN": "आर्थिक जोखीम",
            "mai-IN": "वित्तीय जोखिम",
            "ne-IN": "वित्तीय जोखिम",
            "or-IN": "ଆର୍ଥିକ ବିପଦ",
            "pa-IN": "ਵਿੱਤੀ ਖਤਰਾ",
            "sa-IN": "आर्थिक-संकटम्",
            "sat-IN": "ᱠᱟᱹᱣᱰᱤ ᱟᱱᱟᱴ",
            "sd-IN": "مالي خطرو",
            "ta-IN": "நிதி ஆபத்து",
            "te-IN": "ఆర్థిక ప్రమాదం",
            "ur-IN": "مالی خطرہ",
        }
    },
    "cash_flow": {
        "concept_key": "cash_flow",
        "canonical_definition": "Net movement of cash coming in from platforms and going out to living expenses over time.",
        "short_definition": "Movement of income and outgoing expenses.",
        "terms": {
            "en-IN": "Cash Flow",
            "hi-IN": "कैश फ्लो (नकदी प्रवाह)",
            "bn-IN": "ক্যাশ ফ্লো (নগদ প্রবাহ)",
            "as-IN": "নগদ প্ৰবাহ",
            "brx-IN": "रां बोहैनाय",
            "doi-IN": "रोकड़ बहाव",
            "gu-IN": "રોકડ પ્રવાહ",
            "kn-IN": "ನಗದು ಹರಿವು",
            "ks-IN": "نقد کا بہاؤ",
            "kok-IN": "रोख प्रवाह",
            "ml-IN": "പണപ്രവാഹം",
            "mni-IN": "শেল চৎথোক-চৎশিন",
            "mr-IN": "रोख प्रवाह",
            "mai-IN": "रोकड़ प्रवाह",
            "ne-IN": "नगद प्रवाह",
            "or-IN": "ନଗଦ ପ୍ରବାହ",
            "pa-IN": "ਨਕਦੀ ਪ੍ਰਵਾਹ",
            "sa-IN": "रोकड-प्रवाहः",
            "sat-IN": "ᱠᱟᱹᱣᱰᱤ ᱞᱤᱸᱜᱤᱱ",
            "sd-IN": "ڪيش فلو",
            "ta-IN": "பணப் பாய்ச்சல்",
            "te-IN": "నగదు ప్రవాహం",
            "ur-IN": "نقد کا بہاؤ",
        }
    },
    "goal": {
        "concept_key": "goal",
        "canonical_definition": "A ring-fenced financial objective with a target balance and planned completion horizon.",
        "short_definition": "Dedicated savings target with milestones.",
        "terms": {
            "en-IN": "Goal",
            "hi-IN": "लक्ष्य",
            "bn-IN": "লক্ষ্য",
            "as-IN": "লক্ষ্য",
            "brx-IN": "थांखि",
            "doi-IN": "मकसद",
            "gu-IN": "ધ્યેય",
            "kn-IN": "ಗುರಿ",
            "ks-IN": "ہدف",
            "kok-IN": "ध्येय",
            "ml-IN": "ലക്ഷ്യം",
            "mni-IN": "পান্দম",
            "mr-IN": "ध्येय",
            "mai-IN": "लक्ष्य",
            "ne-IN": "लक्ष्य",
            "or-IN": "ଲକ୍ଷ୍ୟ",
            "pa-IN": "ਨਿਸ਼ਾਨਾ",
            "sa-IN": "लक्ष्यम्",
            "sat-IN": "ᱡᱚᱥ",
            "sd-IN": "مقصد",
            "ta-IN": "இலக்கு",
            "te-IN": "లక్ష్యం",
            "ur-IN": "ہدف",
        }
    },
    "data_readiness": {
        "concept_key": "data_readiness",
        "canonical_definition": "Percentage of required account history and verified inflows needed for high-confidence decisions.",
        "short_definition": "History completeness driving algorithmic certainty.",
        "terms": {
            "en-IN": "Data Readiness",
            "hi-IN": "डेटा तत्परता",
            "bn-IN": "তথ্যের প্রস্তুতি",
            "as-IN": "তথ্যৰ প্ৰস্তুতি",
            "brx-IN": "खारि थियारि",
            "doi-IN": "डेटा तैयारी",
            "gu-IN": "ડેટા સજ્જતા",
            "kn-IN": "ಡೇಟಾ ಸನ್ನದ್ಧತೆ",
            "ks-IN": "ڈیٹا کی تیاری",
            "kok-IN": "डेटा तयारी",
            "ml-IN": "ഡാറ്റാ സന്നദ്ധത",
            "mni-IN": "ই-পাউগী থৌরাং",
            "mr-IN": "डेटा सज्जता",
            "mai-IN": "डेटा तत्परता",
            "ne-IN": "डेटा तत्परता",
            "or-IN": "ତଥ୍ୟ ପ୍ରସ୍ତୁତି",
            "pa-IN": "ਡੇਟਾ ਤਿਆਰੀ",
            "sa-IN": "दत्त-सज्जता",
            "sat-IN": "ᱰᱟᱴᱟ ᱥᱟᱯᱲᱟᱣ",
            "sd-IN": "ڊيٽا جي تياري",
            "ta-IN": "தரவு தயார்நிலை",
            "te-IN": "డేటా సంసిద్ధత",
            "ur-IN": "ڈیٹا کی تیاری",
        }
    },
    "expected_income": {
        "concept_key": "expected_income",
        "canonical_definition": "Anticipated future earnings modeled from recurring transaction streams and seasonal gig volatility.",
        "short_definition": "Modeled earnings anticipated in the upcoming cycle.",
        "terms": {
            "en-IN": "Expected Income",
            "hi-IN": "अपेक्षित आय",
            "bn-IN": "প্রত্যাশিত আয়",
            "as-IN": "প্ৰত্যাশিত আয়",
            "brx-IN": "मिजिंथारनाय आरजि",
            "doi-IN": "उम्मीदी आमदनी",
            "gu-IN": "અપેક્ષિત આવક",
            "kn-IN": "ನಿರೀಕ್ಷಿತ ಆದಾಯ",
            "ks-IN": "متوقع آمدنی",
            "kok-IN": "अपेक्षित येणावळ",
            "ml-IN": "പ്രതീക്ഷിക്കുന്ന വരുമാനം",
            "mni-IN": "আশাকুম্বা ইনকম",
            "mr-IN": "अपेक्षित उत्पन्न",
            "mai-IN": "अपेक्षित आय",
            "ne-IN": "अपेक्षित आम्दानी",
            "or-IN": "ପ୍ରତ୍ୟାଶିତ ଆୟ",
            "pa-IN": "ਸੰਭਾਵਿਤ ਆਮਦਨ",
            "sa-IN": "प्रत्याशित-आयः",
            "sat-IN": "ᱟᱥᱟ ᱟᱨᱡᱟᱣ",
            "sd-IN": "متوقع آمدني",
            "ta-IN": "எதிர்பார்க்கப்படும் வருமானம்",
            "te-IN": "ఆశించిన ఆదాయం",
            "ur-IN": "متوقع آمدنی",
        }
    },
    "financial_surplus": {
        "concept_key": "financial_surplus",
        "canonical_definition": "The net positive cash available after strictly reserving for essential living costs and protected floor.",
        "short_definition": "Net cash remaining after essential expenses and protected reserves.",
        "terms": {
            "en-IN": "Financial Surplus",
            "hi-IN": "वित्तीय अधिशेष",
            "bn-IN": "আর্থিক উদ্বৃত্ত",
            "as-IN": "বিত্তীয় ৰাহি",
            "brx-IN": "रांखान्थियारि उब्रुं",
            "doi-IN": "माली बचत",
            "gu-IN": "નાણાકીય પુરાંત",
            "kn-IN": "ಹಣಕಾಸಿನ ಉಳಿಕೆ",
            "ks-IN": "مالیاتی بچت",
            "kok-IN": "वित्तीय आधिक्य",
            "ml-IN": "സാമ്പത്തിക മിച്ചം",
            "mni-IN": "শেন-থুমগী হেমহৌবা",
            "mr-IN": "आर्थिक अधिशेष",
            "mai-IN": "वित्तीय अधिशेष",
            "ne-IN": "वित्तीय बचत",
            "or-IN": "ଆର୍ଥିକ ବଳକା",
            "pa-IN": "ਵਿੱਤੀ ਵਾਧਾ",
            "sa-IN": "वित्तीय-अतिरेकः",
            "sat-IN": "ᱠᱟᱹᱣᱰᱤ ᱵᱟᱹᱲᱛᱤ",
            "sd-IN": "مالي اضافو",
            "ta-IN": "நிதி உபரி",
            "te-IN": "ఆర్థిక మిగులు",
            "ur-IN": "مالیاتی بچت",
        }
    },
    "income_shortfall": {
        "concept_key": "income_shortfall",
        "canonical_definition": "The gap between actual realized earnings and non-negotiable living obligations during drought periods.",
        "short_definition": "Deficit when earnings fall below essential living costs.",
        "terms": {
            "en-IN": "Income Shortfall",
            "hi-IN": "आय की कमी",
            "bn-IN": "আয় ঘাটতি",
            "as-IN": "আয়ৰ ঘাটি",
            "brx-IN": "आरजि खमथि",
            "doi-IN": "आमदनी कमी",
            "gu-IN": "આવકની ઘટ",
            "kn-IN": "ಆದಾಯ ಕೊರತೆ",
            "ks-IN": "آمدنی کی کمی",
            "kok-IN": "येणावळीची तूट",
            "ml-IN": "വരുമാന കമ്മി",
            "mni-IN": "ইনকম হন্থবা",
            "mr-IN": "उत्पन्नातील तूट",
            "mai-IN": "आय घाटा",
            "ne-IN": "आम्दानी घाटा",
            "or-IN": "ଆୟ ନିଅଣ୍ଟ",
            "pa-IN": "ਆਮਦਨ ਘਾਟਾ",
            "sa-IN": "आय-न्यूनता",
            "sat-IN": "ᱟᱨᱡᱟᱣ ᱠᱚᱢ",
            "sd-IN": "آمدني گھٽتائي",
            "ta-IN": "வருமானப் பற்றாக்குறை",
            "te-IN": "ఆదాయ లోటు",
            "ur-IN": "آمدنی کی کمی",
        }
    },
    "available_safe_buffer": {
        "concept_key": "available_safe_buffer",
        "canonical_definition": "The liquid reserve portion available for deployment without compromising core emergency coverage.",
        "short_definition": "Liquid funds immediately accessible without risking baseline security.",
        "terms": {
            "en-IN": "Available Safe Buffer",
            "hi-IN": "उपलब्ध सुरक्षित बफर",
            "bn-IN": "উপলব্ধ নিরাপদ বাফার",
            "as-IN": "উপলব্ধ সুৰক্ষিত বাফাৰ",
            "brx-IN": "मोननो हानाय रैखा बाफार",
            "doi-IN": "मौजूद सुरक्षित बफर",
            "gu-IN": "ઉપલબ્ધ સુરક્ષિત બફર",
            "kn-IN": "ಲಭ್ಯವಿರುವ ಸುರಕ್ಷಿತ ಬಫರ್",
            "ks-IN": "دستیاب محفوظ بفر",
            "kok-IN": "उपलब्ध सुरक्षित बफर",
            "ml-IN": "ലഭ്യമായ സുരക്ഷിത ബഫർ",
            "mni-IN": "ফংবা য়াবা ঙাকথোক বাফার",
            "mr-IN": "उपलब्ध सुरक्षित बफर",
            "mai-IN": "उपलब्ध सुरक्षित बफर",
            "ne-IN": "उपलब्ध सुरक्षित बफर",
            "or-IN": "ଉପଲବ୍ଧ ସୁରକ୍ଷିତ ବଫର",
            "pa-IN": "ਉਪਲਬਧ ਸੁਰੱਖਿਅਤ ਬਫ਼ਰ",
            "sa-IN": "उपलब्ध-सुरक्षित-बफरः",
            "sat-IN": "ᱧᱟᱢᱚᱜ ᱨᱩᱠᱷᱤᱭᱟᱹ ᱵᱟᱯᱷᱟᱨ",
            "sd-IN": "دستياب محفوظ بفر",
            "ta-IN": "கிடைக்கக்கூடிய பாதுகாப்பான பஃபர்",
            "te-IN": "అందుబాటులో ఉన్న సురక్షిత బఫర్",
            "ur-IN": "دستیاب محفوظ بفر",
        }
    },
    "obligation": {
        "concept_key": "obligation",
        "canonical_definition": "A mandatory non-negotiable expenditure or recurring financial commitment such as rent, EMI, or insurance.",
        "short_definition": "Mandatory commitment such as rent, loan EMI, or essential bills.",
        "terms": {
            "en-IN": "Obligation",
            "hi-IN": "अनिवार्य देयता",
            "bn-IN": "অপরিহার্য বাধ্যবাধকতা",
            "as-IN": "বাধ্যতামূলক দেনা",
            "brx-IN": "गोनांथार होनांगौ",
            "doi-IN": "ज़रूरी देनदारी",
            "gu-IN": "ફરજિયાત જવાબદારી",
            "kn-IN": "ಕಡ್ಡಾಯ ಹೊಣೆಗಾರಿಕೆ",
            "ks-IN": "لازمی ادائیگی",
            "kok-IN": "अनिवार्य देणी",
            "ml-IN": "ബാധ്യത",
            "mni-IN": "তৌদবা য়াদবা ইথিল",
            "mr-IN": "अनिवार्य दायित्व",
            "mai-IN": "अनिवार्य देयता",
            "ne-IN": "अनिवार्य दायित्व",
            "or-IN": "ଅପରିହାର୍ଯ୍ୟ ଦେୟ",
            "pa-IN": "ਲਾਜ਼ਮੀ ਦੇਣਦਾਰੀ",
            "sa-IN": "अनिवार्य-कर्तव्यम्",
            "sat-IN": "ᱮᱢᱚᱜ ᱞᱟᱹᱠᱛᱤ",
            "sd-IN": "لازمي ذميواري",
            "ta-IN": "கட்டாயக் கடப்பாடு",
            "te-IN": "తప్పనిసరి బాధ్యత",
            "ur-IN": "لازمی ذمہ داری",
        }
    },
    "forecast": {
        "concept_key": "forecast",
        "canonical_definition": "Deterministic cash-flow simulation projecting account balances over a forward-looking horizon.",
        "short_definition": "Forward-looking cash projection across upcoming weeks.",
        "terms": {
            "en-IN": "Forecast",
            "hi-IN": "पूर्वानुमान",
            "bn-IN": "পূর্বাভাস",
            "as-IN": "পূৰ্বানুমান",
            "brx-IN": "सिगांनि सानथौ",
            "doi-IN": "अगाऊ अंदाज़ा",
            "gu-IN": "પૂર્વાનુમાન",
            "kn-IN": "ಮುನ್ಸೂಚನೆ",
            "ks-IN": "پیش گوئی",
            "kok-IN": "अंदाज",
            "ml-IN": "പ്രവചനം",
            "mni-IN": "মাংজৌননা খঙদোকপা",
            "mr-IN": "अंदाज",
            "mai-IN": "पूर्वानुमान",
            "ne-IN": "पूर्वानुमान",
            "or-IN": "ପୂର୍ବାନୁମାନ",
            "pa-IN": "ਪੂਰਵ ਅਨੁਮਾਨ",
            "sa-IN": "पूर्वानुमानम्",
            "sat-IN": "ᱞᱟᱦᱟ ᱞᱮᱠᱷᱟ",
            "sd-IN": "اڳڪٿي",
            "ta-IN": "முன்கணிப்பு",
            "te-IN": "ముందస్తు అంచనా",
            "ur-IN": "پیش گوئی",
        }
    },
    "capital_preservation": {
        "concept_key": "capital_preservation",
        "canonical_definition": "The strict financial principle preventing capital erosion below safe liquidity thresholds.",
        "short_definition": "Protection of principal liquidity against down-cycles.",
        "terms": {
            "en-IN": "Capital Preservation",
            "hi-IN": "पूंजी संरक्षण",
            "bn-IN": "মূলধন সংরক্ষণ",
            "as-IN": "মূলধন সুৰক্ষা",
            "brx-IN": "मुलधन रैखाथि",
            "doi-IN": "पूंजी सुरक्षा",
            "gu-IN": "મૂડી સંરક્ષણ",
            "kn-IN": "ಬಂಡವಾಳ ಸಂರಕ್ಷಣೆ",
            "ks-IN": "سرمائے کا تحفظ",
            "kok-IN": "भांडवल संरक्षण",
            "ml-IN": "മൂലധന സംരക്ഷണം",
            "mni-IN": "লল্লুক ঙাকশেনবা",
            "mr-IN": "भांडवल संरक्षण",
            "mai-IN": "पूँजी संरक्षण",
            "ne-IN": "पुँजी संरक्षण",
            "or-IN": "ମୂଳଧନ ସଂରକ୍ଷଣ",
            "pa-IN": "ਪੂੰਜੀ ਸੰਭਾਲ",
            "sa-IN": "मूलधन-संरक्षणम्",
            "sat-IN": "ᱯᱩᱸᱡᱤ ᱨᱩᱠᱷᱤᱭᱟᱹ",
            "sd-IN": "سرمائي جي حفاظت",
            "ta-IN": "மூலதனப் பாதுகாப்பு",
            "te-IN": "మూలధన పరిరక్షణ",
            "ur-IN": "سرمائے کا تحفظ",
        }
    },
    "data_quality": {
        "concept_key": "data_quality",
        "canonical_definition": "The reliability, completeness, and recency of transaction telemetry provided by connected bank feeds.",
        "short_definition": "Health and recency of connected transaction streams.",
        "terms": {
            "en-IN": "Data Quality",
            "hi-IN": "डेटा गुणवत्ता",
            "bn-IN": "ডেটা গুণমান",
            "as-IN": "তথ্যৰ মান",
            "brx-IN": "डाटा गुन",
            "doi-IN": "डेटा क्वालिटी",
            "gu-IN": "ડેટા ગુણવત્તા",
            "kn-IN": "ಡೇಟಾ ಗುಣಮಟ್ಟ",
            "ks-IN": "ڈیٹا معیار",
            "kok-IN": "डेटा प्रत",
            "ml-IN": "ഡാറ്റാ ഗുണനിലവാരം",
            "mni-IN": "ই-পাউগী মগুন",
            "mr-IN": "डेटा गुणवत्ता",
            "mai-IN": "डेटा गुणवत्ता",
            "ne-IN": "डेटा गुणस्तर",
            "or-IN": "ତଥ୍ୟ ଗୁଣବତ୍ତା",
            "pa-IN": "ਡੇਟਾ ਗੁਣਵੱਤਾ",
            "sa-IN": "दत्त-गुणवत्ता",
            "sat-IN": "ᱰᱟᱴᱟ ᱜᱩᱱ",
            "sd-IN": "ڊيٽا معيار",
            "ta-IN": "தரவு தரம்",
            "te-IN": "డేటా నాణ్యత",
            "ur-IN": "ڈیٹا کا معیار",
        }
    }
}


def get_glossary_term(concept_key: str, locale: str = "en-IN") -> str:
    """Returns the approved localized term for a given financial concept."""
    concept = FINANCIAL_GLOSSARY.get(concept_key)
    if not concept:
        return concept_key.replace("_", " ").title()
    
    terms = concept.get("terms", {})
    if locale in terms:
        return terms[locale]
    
    # Fallback to English
    return terms.get("en-IN", concept_key)


def get_locale_glossary(locale: str = "en-IN") -> Dict[str, Dict[str, str]]:
    """Returns all glossary concepts localized for the specified locale."""
    result = {}
    for key, concept in FINANCIAL_GLOSSARY.items():
        localized_term = get_glossary_term(key, locale)
        result[key] = {
            "term": localized_term,
            "definition": concept["canonical_definition"],
            "short_definition": concept["short_definition"],
        }
    return result


get_glossary_for_locale = get_locale_glossary

